### ISSUE TITLE
不能正常编译

### ISSUE THREAD

**Issue by uplusplus** [x-hansong/aSpice#1]
1 NDK编译失败
2 APK编译完成，运行提示class not found exception

**Comment by x-hansong** [comment]
我是根据这个修改的，这里有详细的编译过程。https://github.com/iiordanov/remote-desktop-clients
ndk版本要选择ndk r9
这个项目比较旧，所以尽量不要用太新的库。根据项目编译时的库选择相应的版本。
具体的步骤我也忘了，主要是库的版本问题。
